# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**3)** Cree un array tridimensional de flotantes `b` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [95]:
# 2.1)
a = np.array([1,2,3])
b = np.array([[1.5,2,3], [4,5,6]])
c = np.array([[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]])

print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 3)


## **Ejercicio 3)** Inicializando arrays

**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**5)** Utilice `np.full` para crear un array bidimensional de entradas iguales a `7`, y de dimesiones `(2,2)`.

**6)** Utilice `np.eye` para crear una matriz identidad de dimensiones 2x2.

**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [81]:
# 3.1)
zeros = np.zeros((3,4))
print(zeros.shape)

ones = np.ones((2,3,4))
print(ones.shape)

d = np.arange(10,25,5)
print(d)

equiespaciados = np.linspace(0,9,9)
print(equiespaciados)

e = np.full((2,2), 7)
print(e)

f = np.eye(2)
print(f)

random = np.random.random((2,2))
print(random)

empty = np.empty((3,2))
print(empty)

(3, 4)
(2, 3, 4)
[10 15 20]
[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875 9.   ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.94190581 0.71804012]
 [0.33379285 0.35098995]]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]


## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**2)** Utilizando la función `len()`, determine el *largo* del array `a`.

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [82]:
# 4.1)
print(a.shape)
print(len(a))
print(b.ndim)
print(e.size)
print(b.dtype)
print(b.dtype.name)
b = b.astype(int)
print(b.dtype)

(3,)
3
2
4
float64
float64
int32


## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

**2)** Cree un array que contenga elementos de tipo `np.float32`.

**3)** Cree un array que contenga elementos de tipo `np.complex128`.

**4)** Cree un array que contenga elementos de tipo `np.bool`.

**5)** Cree un array que contenga elementos de tipo `np.object`.

**6)** Cree un array que contenga elementos de tipo `np.string_`.

**7)** Cree un array que contenga elementos de tipo `np.unicode_`.

In [44]:
# 5.1)
int64 = np.random.random(4).astype(np.int64)
float32 = np.random.random(4).astype(np.float32)
complex128 = np.random.random(4).astype(np.complex128)
bool = np.random.random(4) > 0.5
object = np.random.random(4).astype(np.object_)
string = np.random.random(4).astype(np.string_)
unicode = np.random.random(4).astype(np.unicode_)

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la suma `a+b`. Explique lo que ocurre.

**3)** Compare el anterior resultado con el uso de `np.substract`.

**4)** Calcule la suma `a-b` de los arrays `a` y `b`.

**5)** Compare el anterior resultado con el uso de `np.add`.

**6)** Calcule la división punto a punto  `a/b` de `a` y `b`.

**7)** Compare el anterior resultado con el uso de `np.divide`.

**8)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

**9)** Compare el anterior resultado con el uso de `np.multiply`.

**10)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

**11)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

**12)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

**13)** Calcule el coseno punto a punto  `np.sin(b)` de `b`.

**14)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**16)** Compare el anterior resultado con el uso de `np.dot`.

**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [115]:
# 6.1)
g = a - b
print(g)

#A pesar de tener distintas dimensiones Python replica el array 'a' para llevarlo a la misma dimensión que 'b' y efectuar la resta

h = np.subtract(a,b)
print(h)

print(a+b)
print(np.add(a,b))

print(a/b)
np.divide(a,b)

print(a*b)
print(np.multiply(a,b))

print(np.exp(b))

print(np.sqrt(b))

print(np.sin(a))
print(np.sin(b))

print(np.log(a))

print(e.dot(f))
print(np.dot(e,f))

'''
Dot product of two arrays. Specifically,

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:
'''

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[0.84147098 0.90929743 0.14112001]
[[ 0.99749499  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[0.         0.69314718 1.09861229]
[[7. 7.]
 [7. 7.]]
[[7. 7.]
 [7. 7.]]


'\nDot product of two arrays. Specifically,\n\nIf both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).\n\nIf both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.\n\nIf either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.\n\nIf a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.\n\nIf a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:\n'

## **Ejercicio 7)** Comparando arrays

**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [63]:
# 7.1)
print(a==b)
print(b < 2)
print(np.array_equal(a,b))

[[False  True  True]
 [False False False]]
[[ True False False]
 [False False False]]
False


## **Ejercicio 8)** *Copiando* arrays

**1)** Use `.view()` para crear una vista del array `a`.

**2)** Use `.copy()` para crear una copa del array `a`.

In [65]:
# 8.1)
a_view = a.view() #Si modificamos a, se modifica a_view
a_copy = a.copy()

print(a_view)
print(a_copy)

[1 2 3]
[1 2 3]
[10  2  3]
[1 2 3]


## **Ejercicio 9)** Ordenado

**1)** Use `.sort()` para ordenar los elementos de `a`.

**2)** Ordene los elementos de `a` a lo largo del eje `0`. Explique.

In [70]:
# 9.1)

a.sort()
print(a)

a.sort(axis=0) #Se ordena de acuerdo al primer eje o dimensión
print(a)

[1 2 3]
[1 2 3]


## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays

**1)** Seleccione el segundo elemento de `a`.

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**3)** Seleccione el rango `[0:2]` de elementos de `a`.

**4)** Seleccione los elementos de `b` en el rango `[0:2]` y la columna `1`.

**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**6)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**8)** Seleccione los elementos de `a` que sean menores que dos.

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [100]:
# 10.1)
print(a[1])
print(b[1,2])
print(a[0:2])
#print(b[a[0:2]-1, 1]) #Hay un error de enunciado: a=[1,2,3] y a[0:2]=[1,2], pero b solo tiene columnas 0 y 1, no tiene columna 2, por eso le resto 1
print(b[:2, 1]) #Hay un error de enunciado: a=[1,2,3] y a[0:2]=[1,2], pero b solo tiene columnas 0 y 1, no tiene columna 2, por eso le resto 1
print(b[0:1,:])
print(c[1,...])
print(a[::-1])
print(a[a<2])
print([b[i] for i in [(1,0),(0,1),(1,2),(0,0)]])

fila = [1,0,1,0]
columna = [0,1,2,0]

print([b[fila[i],columna[i]] for i,_ in enumerate(fila)])



2
6.0
[1 2]
[2. 5.]
[[1.5 2.  3. ]]
[[3. 2. 1.]
 [4. 5. 6.]]
[3 2 1]
[1]
[4.0, 2.0, 6.0, 1.5]
[4.0, 2.0, 6.0, 1.5]


## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [101]:
# 11.1)
i = np.transpose(b)
print(i)
print(b)
print(i.T)


[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para *achatar* el array `b`.

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.

**3)** Que indica aquí el signo negativo del segundo índice?

In [103]:
# 12.1)
print(b.ravel())
print(g.reshape((3,-2)))

[1.5 2.  3.  4.  5.  6. ]
[[ 0  0]
 [ 0 -3]
 [-3 -3]]


## **Ejercicio 13)** Agregando y quitando elementos

**1)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [124]:
# 13.1)
h.resize((2,6))

print(h)
print(g)
new = np.append(h,g)
print(new) #Numpy aplana los arrays para que tengan la misma dimensión

a_new = np.insert(a,1,5)
print(a_new)

a_delete = np.delete(a_new,[1])
print(a_delete)

[[-0.5  0.   0.  -3.  -3.  -3. ]
 [ 0.   0.   0.   0.   0.   0. ]]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[-0.5  0.   0.  -3.  -3.  -3.   0.   0.   0.   0.   0.   0.  -0.5  0.
  0.  -3.  -3.  -3. ]
[1 5 2 3]
[1 2 3]


## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.row_stack()` para apilar verticalmente los arrays `e` y `f`.

**d)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.

**e)** Use `np.column_stack()` para apilar horizontalmente los arrays `a` y `d`.

In [130]:
# 14.1)
res = np.concatenate((a,d))
print(res)

res_1 = np.vstack((a,b))
print(res_1)

res_2 = np.row_stack((e,f))
print(res_2)

res_3 = np.hstack((e,f))
print(res_3)

res_4 = np.column_stack((a,d))
print(res_4)

[ 1  2  3 10 15 20]
[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]
[[7. 7.]
 [7. 7.]
 [1. 0.]
 [0. 1.]]
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]


## **Ejercicio 15)** *Separando* arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por

    [[1, 2, 3, 4],
      [2, 0, 0, 2],
      [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

In [133]:
# 15.1)

split = np.hsplit(a,3)
print(split)

split_v = np.vsplit(c,2)
print(split_v)

z = np.array([[1, 2, 3, 4],
      [2, 0, 0, 2],
      [3, 1, 1, 0]])

split_1 = np.split(z,2,axis=1)
print(split_1)

[array([1]), array([2]), array([3])]
[array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
        [4., 5., 6.]]])]
[array([[1, 2],
       [2, 0],
       [3, 1]]), array([[3, 4],
       [0, 2],
       [1, 0]])]


## **Ejercicio 16)** Generando números aleatorios

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.

**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.

In [181]:
# 16.1)

num = np.float64(np.random.random())
num1 = np.float64(np.random.random(10))
num2 = np.float64(np.random.random((3,4)))
num3 = np.float64(np.random.randn())
num4 = np.float64(5 + np.sqrt(9) * np.random.randn())
num5 = np.float64(-1 + np.sqrt(2) * np.random.randn(3,2,3))
num6 = np.int64(np.random.randint(0,4))
num7 = np.int64(np.random.randint(10,16))
num8 = np.int64(np.random.randint(0,1,size=(3,2,3)))
elemento = np.random.choice(["perro","gato","loro","caballo","vaca"])
array = np.random.choice(["perro","gato","loro","caballo","vaca"], size=(3,3))
array = np.random.choice(["perro","gato","loro","caballo","vaca"], size=(3,3,3), p=[8/16,4/16,2/16,1/16,1/16])

lista_n = np.arange(10)
permutacion_aleatoria = np.random.permutation(lista_n)
permutacion_shuffle = np.random.shuffle(lista_n)

array([2, 5, 3, 0, 1, 7, 9, 6, 4, 8])